# Generated by Django 5.2.5 on 2025-08-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userkeypair'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
